version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # We use the local host Ollama, so no container for it.
  # Ollama must be running on the host machine.

volumes:
  postgres_data:
  qdrant_data:
